#pragma once
#include "sdkconfig.h"
#ifndef CONFIG_FALL_TRIGGER_MODEL
#define CONFIG_FALL_TRIGGER_MODEL 0
#endif
#ifndef CONFIG_FALL_CASCADE
#define CONFIG_FALL_CASCADE 0
#endif
#ifndef CONFIG_FALL_DEBUG_LOGS
#define CONFIG_FALL_DEBUG_LOGS 0
#endif
#ifndef CONFIG_FALL_LEGACY_POWER_BASELINE
#define CONFIG_FALL_LEGACY_POWER_BASELINE 0
#endif

#ifndef CONFIG_FALL_INTERNAL_ARENA
#define CONFIG_FALL_INTERNAL_ARENA 0
#endif
