[platformio]
src_dir = main
default_envs = m5stickc-plus2-ble

[env:m5stickc-plus2-ble]
platform = espressif32@6.13.0
board = m5stick-c
framework = espidf
monitor_speed = 115200
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = partitions.csv
board_build.embed_files = main/model.tflite
extra_scripts = pre:../tools/build_guard.py
